version: '3.8'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dev_php
    volumes:
      - ./www:/var/www
    networks:
      - app-network
    environment:
      PHP_IDE_CONFIG: serverName=Docker
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: dev_nginx
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/locations:/etc/nginx/conf.d/locations
    depends_on:
      - php
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
